module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                //内置已经有@===>src
                "assets":"@/assets",
                "common":"@/common",
                "components":"@/components",
                "network":"@/network",
                "views":"@/views"
            }
        }

    },
    devServer:{
        host:'localhost',
        port:8080,
        proxy:{
            //意思是当我们访问xxxx/api/xxx的时候，就会被代理到
            //https://www.imooc.com'中
            '/api':{
                target:'http://mall-pre.springboot.cn',
                changeOrigin:true,
                pathRewrite:{
                    //https://www.imooc.com/api代理xxxx/api
                    '/api':''
                }
            }
        }
    }

}